package blash10x.ocrtranslator.service;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.atomic.AtomicReference;

/**
 * Author: myungsik.sung@gmail.com
 */
public class GeminiWebApiService extends AbstractProcessService {
  private final Map<String, String> cache = new HashMap<>();
  private final ResultHandler resultHandler;
  private final AtomicReference<StringBuilder> resultReference =  new AtomicReference<>();

  public GeminiWebApiService() {
    super("gemini-webapi");
    ConfigLoader configLoader = ConfigLoader.getConfigLoader();
    String command = configLoader.getProperty("translation.gemini-webapi.command");
    start(command);

    resultHandler = new ResultHandler(process, resultReference);
    resultHandler.start();
  }

  public String translate(String textToTranslate) {
    return cache.computeIfAbsent(textToTranslate, key -> _translate(textToTranslate));
  }

  private String _translate(String textToTranslate) {
    OutputStream os = process.getOutputStream(); // 프로세스의 입력 스트림 가져오기
    BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(os));
    try {
      resultReference.set(new StringBuilder());
      writer.write(textToTranslate + "\nEOF\n");
      writer.flush(); // 버퍼 비우기 (중요: 데드락 발생 가능성)

      synchronized (resultHandler) {
        resultHandler.wait();
      }
      return resultReference.get().toString();
    } catch (Exception e) {
      return e.toString();
    }
  }

  private static class ResultHandler extends Thread {
    private final Process process;
    private final AtomicReference<StringBuilder> resultReference;

    public ResultHandler(Process process, AtomicReference<StringBuilder> resultReference) {
      this.process = process;
      this.resultReference = resultReference;
    }

    @Override
    public void run() {
      try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()))) {
        boolean found = false;
        for (String line; (line = reader.readLine()) != null; ) {
          System.out.println(line);
          if (line.contains("응답:")) {
            found = true;
          } else if (found && line.contains("generated by")) {
            synchronized (this) {
              notify();
            }
            found = false;
          } else if (found) {
            resultReference.get().append(line).append("\n");
          }
        }
      } catch (Exception e) {
        System.err.println(e);
      }
    }
  }
}
