package blash10x.ocrtranslator.service;

import java.util.HashMap;
import java.util.Map;
import java.util.function.Consumer;

/**
 * Author: myungsik.sung@gmail.com
 */
public class GeminiWebApiService extends AbstractProcessService {
  private final Map<String, String> cache = new HashMap<>();
  private final ResultCollector resultCollector = new ResultCollector();

  public GeminiWebApiService() {
    super("gemini-webapi");

    String command = configLoader.getProperty("translation.gemini-webapi.command");
    start(command, resultCollector);
  }

  public String translate(String textToTranslate) {
    return cache.computeIfAbsent(textToTranslate, key -> _translate(textToTranslate));
  }

  private String _translate(String textToTranslate) {
    try {
      writeToProcess(textToTranslate + "\nEOF\n"); // translation command:

      synchronized (resultCollector) {
        resultCollector.wait();
      }
      return resultCollector.getResult();
    } catch (Exception e) {
      return e.toString();
    }
  }

  public static class ResultCollector implements Consumer<String> {
    private final StringBuilder builder = new StringBuilder();
    private boolean found = false;
    private String result;

    @Override
    public void accept(String str) {
      if (str.contains("응답:")) {
        found = true;
      } else if (found && str.contains("generated by")) {
        synchronized (this) {
          result = builder.toString();
          builder.setLength(0);
          notify();
        }
        found = false;
      } else if (found) {
        builder.append(str).append("\n");
      }
    }

    private String getResult() {
      return result;
    }
  }
}
